demo_mysql:
  target: dev
  outputs:
    dev:
      type: mysql
      server: terraform-20241130190851022500000001.cvgsvodwblg4.us-east-1.rds.amazonaws.com
      port: 3306  # optional
      database: salesforce # optional, should be same as schema
      schema: public
      username: admin
      password: Senha_0911
      driver: MySQL ODBC 8.0 ANSI Driver
    prod:
      type: mysql
      server: [server/host]
      port: [port]  # optional
      database: [schema] # optional, should be same as schema
      schema: [schema]
      username: [username]
      password: [password]
      driver: MySQL ODBC 8.0 ANSI Driver
    local:
      type: mysql
      server: localhost
      port: 3306  # optional
      database: salesforce # optional, should be same as schema
      schema: public
      username: admin
      password: Senha_0911
      driver: MySQL ODBC 8.0 ANSI Driver