demo_mysql:
  outputs:
    dev:
      database: '{{ env_var(''DATABASE_NAME'') }}'
      driver: MySQL ODBC 8.0 ANSI Driver
      password: '{{ env_var(''DATABASE_PWD'') }}'
      port: 3306
      schema: '{{ env_var(''DATABASE_SCHEMA'') }}'
      server: '{{ env_var(''DATABASE_URL'') }}'
      type: mysql
      username: '{{ env_var(''DATABASE_USER'') }}'
  target: dev