@startuml data_pipeline
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
title Data Pipeline - Diagramas
footer Disponível em: https://github.com/fabiosantos-info/mackenzie-DBRE
LAYOUT_LEFT_RIGHT()

Person(user, "Usuário")
Person(data_scientist, "Cientista de Dados")

System_Boundary(olap, "OLAP") {

    System_Boundary(dataviz, "Data Visualization") {
        Container(dash, "Dashboard", "Qlik, Power BI", "Tool for dashboard")
    }

    System_Boundary(ml, "Machine Learning") {
        Container(ia, "ML/IA", "Tensor Flow/Sklearning", "")        
    }
    System_Boundary(analytics, "Data Analytics") {

        ContainerDb(silver, "Trusted (Silver)", "Cloud Storage/(Parquet/Avro)")
        Container(transformation_bronze_silver, "Transformation", "dbt", "Padronização e limpeza")

        ContainerDb(gold, "Data Warehouse (Gold)", "Bigquery/snowflake/Redshift")
        Container(transformation_silver_gold, "Transformation", "dbt", "Padronização e limpeza")
    }

    System_Boundary(ingestion, "Data Ingestion(EL)") {
        ContainerDb(bronze, "Raw (Bronze)", "Cloud Storage" )
        Container(extraction, "Extraction", "airbyte", "Extração e carga de dados")
    }
}

System_Boundary(oltp, "OLTP") {
    ContainerDb(external_db, "External databases", "SAP, Totvs")
    ContainerQueue(external_queue, "Data Stream", "Kafka, RabitMQ")
    Container(external_api, "APIs")
    ContainerDb(external_storage, "External storage", "GDrive, Dropbox")
}

Rel(external_db, extraction, "Coletar dados")
Rel(external_queue, extraction, "Coletar dados")
Rel(external_api, extraction, "Coletar dados")
Rel(external_storage, extraction, "Coletar dados")
Rel(extraction, bronze, "Persistir dados")

Rel(oltp, olap, "Fornecer dados")
Rel(ingestion, analytics, "Atualizar dados")


Rel(bronze, transformation_bronze_silver, "Coletar dados")
Rel(transformation_bronze_silver, silver, "Persistir dados transformados")

Rel(silver, transformation_silver_gold, "Coletar dados")
Rel(transformation_silver_gold, gold, "Persistir dados transformados")

Rel(user, dash, "Visualizar")
Rel(dash, gold, "Carregar dados")

Rel(data_scientist, ia, "Criar algoritimos de Machine Learning")
Rel(ia, gold, "Carregar dataset para treinamento")

@enduml